version: '3.8'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  query:
    container_name: query_ms
    restart: always
    ports:
      - "3002:3002"
    build:
      context: ./query
      dockerfile: Dockerfile
    environment:
      RMQ_URL: amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
  posts:
    container_name: posts_ms
    restart: always
    ports:
      - "3000:3000"
    build:
      context: ./posts
      dockerfile: Dockerfile
    environment:
      RMQ_URL: amqp://rabbitmq:5672
    depends_on:
      - query
    links:
      - rabbitmq
  comments:
    container_name: comments_ms
    restart: always
    ports:
      - "3001:3001"
    build:
      context: ./comments
      dockerfile: Dockerfile
    environment:
      RMQ_URL: amqp://rabbitmq:5672
    depends_on:
      - query
    links:
      - rabbitmq
  moderation:
    container_name: moderation_ms
    restart: always
    build:
      context: ./moderation
      dockerfile: Dockerfile
    environment:
      RMQ_URL: amqp://rabbitmq:5672
    depends_on:
      - query
    links:
      - rabbitmq