@BASE_URL=http://localhost:3001

###
GET {{BASE_URL}}/comments?post_id=1c0458ca HTTP/1.1

###
POST {{BASE_URL}}/comments HTTP/1.1
Content-Type: application/json

{
  "comment": "comment 2 with orange",
  "postId": "1c0458ca"
}