apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: sba10/blog_moderation:0.0.1
          env:
            - name: RMQ_URL
              value: "amqps://zftoopxi:yOVEFq9ifu2Io94GKJM0UfJJumROtvx8@beaver.rmq.cloudamqp.com/zftoopxi"
